### ISSUE TITLE
Share User Accounts across multiple Events

### ISSUE THREAD

**Issue by rdunlop** [rdunlop/unicycling-registration#145]
It may be nice to be able to share user accounts across multiple Conventions.

For example: NAUCC occurs each year, and it may be nice to be able to just re-use the same account each year. That way, a Email sign-up/confirmation sequence is not needed.

This will become increasingly important once we re-use www.naucc.com for a future convention, but with a separate "instance" in the backend.

I suspect that sharing accounts throughout ALL conventions is probably not desired, as I think that it might be confusing to be signing up on separate URLS with the same email/password.

THUS, I propose:
- When a new convention is being created/configured, the Administrator(s) can choose "Share User Logins with the following Tenant(s)", which would mean that if a user already has an account there, they would have to use that account, or create a new one.

**Comment by scotthue** [comment]
I don't really see a problem with having one account across all instances.

**Comment by rdunlop** [comment]
Resolved this past winter.
