### ISSUE TITLE
Show All PDF should be a background job

### ISSUE THREAD

**Issue by rdunlop** [rdunlop/unicycling-registration#170]
The "Show all Registrant Summary PDF" should result in a background job which generates the PDFs, and then provides a link to download, with a timestamp.

We should create a "Reports" table, which stores the various reports, and timestamp.

**Comment by scotthue** [comment]
We will be printing these on Monday evening or Tuesday morning, so this is certainly high priority.

**Comment by rdunlop** [comment]
This is now functional. It's not easy to get back to the reports page without typing `/reports` in the URL, but it does generate the large PDF, over a long amount of time, if necessary.
