### ISSUE TITLE
Allow specifying the lane-assignment order for Automatic creation

### ISSUE THREAD

**Issue by rdunlop** [rdunlop/unicycling-registration#175]
when automatically creating heat/lanes, it currently always assigns lanes 1,2,3,4,5,6,7,8

We should allow this to be specified, so that we can do 4.5.3.6...etc etc.

**Comment by scotthue** [comment]
This should be entirely customizable to allow for 5-9 lane tracks as well
as non-usable lanes (due to bad surfaces). But it should suggest the
default options to help the event director remember.

**Comment by rdunlop** [comment]
I believe that this is now complete, with the changes made in a801ea173a095dc6e5c479cfb1de625c1cecf384
