### ISSUE TITLE
Don't allow selection of 16" wheel at UNICON

### ISSUE THREAD

**Issue by rdunlop** [rdunlop/unicycling-registration#177]
It's not a valid Track Racing Wheel size for UNICON.

We should not allow it to be selected.

**Comment by scotthue** [comment]
Perhaps default it to it not being an option but configurable under
advanced settings on event setup in convention setup. The 16" option is
seldom used by anyone.

**Comment by rdunlop** [comment]
resolved by 5141af35176c1106dd3270005e108fd10530e7ff
