### ISSUE TITLE
Overflow is hidden on mobile devices

### ISSUE THREAD

**Issue by scotthue** [rdunlop/unicycling-registration#179]
UDA will be much more frequently used by mobile devices during Unicon and many of the director's features do not work here.

I think it has to do with the `off-canvas-content` CSS, but I am not sure.

**Comment by scotthue** [comment]
Why is this not High Priority any more? This bug was extremely problematic for both me and Patricia at Unicon.

**Comment by rdunlop** [comment]
I de-prioritized this because it did appear that we got through Unicon without it. I'm adding it back to High Priority based on your feedback...but I'm trying to actually get through the "High Priority" work without it growing to encompass all entries.

**Comment by scotthue** [comment]
I understand that not everything can be high priority, but when I prioritize the current issues, this issue is in the top 3 for me. Thanks.

**Comment by rdunlop** [comment]
resolved this week with the change to the menu
