### ISSUE TITLE
Option to export start list CSV always

### ISSUE THREAD

**Issue by scotthue** [rdunlop/unicycling-registration#418]
There are many reasons an event might want the start list as a CSV. I have copied the list of competitors from a table in UDA to an excel sheet countless times for various competitions. There should be the option to export this, independent of the setting chosen for "start line data entry" or any other competition setting. This option should go on the side bar, either next to Start Line, or at the end of the Competitors area.

![screen shot 2017-05-28 at 08 46 03](https://cloud.githubusercontent.com/assets/3074091/26529240/1cb2a456-4382-11e7-8ff5-dfe279ef3097.jpg)

**Comment by rdunlop** [comment]
resolved, now can always export that data.
