### ISSUE TITLE
Time entry columns should not be required for non-timed competitions

### ISSUE THREAD

**Issue by scotthue** [rdunlop/unicycling-registration#419]
See title.

![screen shot 2017-05-28 at 08 53 44](https://cloud.githubusercontent.com/assets/3074091/26529307/5135662c-4383-11e7-957a-070823d3a4f1.jpg)

![screen shot 2017-05-28 at 08 53 36](https://cloud.githubusercontent.com/assets/3074091/26529309/53b2e438-4383-11e7-83a7-c5621dda647d.jpg)

**Comment by rdunlop** [comment]
resolved. now can be set to nil.
