### ISSUE TITLE
Emails sent from the system should have the "Reply-to" set to the organizer's e-mail

### ISSUE THREAD

**Issue by rdunlop** [rdunlop/unicycling-registration#425]
When an administrator sends bulk e-mails to people for a competition, it comes from "registration@unicycling-software.com"....if a user replies to that e-mail, only Robin recieves it.

Perhaps it would be better to add a "reply-to" header, so that replies get sent to the "Contact email" specified in the particular convention?

@scotthue What do you think?

**Comment by scotthue** [comment]
Can the reply-to header to go multiple addresses?

**Comment by rdunlop** [comment]
@scotthue yes, you can have multiple reply-to targets.
