### ISSUE TITLE
Auto redirect to HTTPS

### ISSUE THREAD

**Issue by scotthue** [rdunlop/unicycling-registration#472]
If I go to many (but not all?) UDA tenants, they default to HTTP. All of the ones I tested still work if I manually enter the URL with HTTPS. Why is this not the default?

**Comment by rdunlop** [comment]
Resolved with https://github.com/rdunlop/unicycling-registration/pull/477

Note: the currently implemented code only creates new SSL Certs once a week (Sunday night, I think).

So any new conventions will not be available immediately...as the cert is not created on-demand.

It should be possible to make the code fetch a new cert on-demand when a new convention is created...but it's not set up for that right now
