### ISSUE TITLE
When event is minutes_seconds_hundreths the CSV import column descriptions should match

### ISSUE THREAD

**Issue by scotthue** [rdunlop/unicycling-registration#544]
Event is minutes_second_hundreths but still shows this:

CSV Import Instructions
Please import a Comma-Separated-File (Windows CSV Format) file with the following format:
Column 1: ID
Column 2: Minutes
Column 3: Seconds
**Column 4: Thousands**
Column 5: "DQ" or "DNF" or empty

**Comment by rdunlop** [comment]
We ran into something similar at NAUCC when we were trying to import hours-minutes-seconds

**Comment by rdunlop** [comment]
fixed by #1027
