### ISSUE TITLE
Display date/Time in local format

### ISSUE THREAD

**Issue by rdunlop** [rdunlop/unicycling-registration#582]
When displaying date/time, the display is always UTC.

This is always confusing to the end-user.

We have 2 options here.
1) Add Javascript which translates the UTC into the timezone of the local browser
2) Add a setting which specifies the Timezone of the convention, and display all date/times in that TimeZone.

Both of these are approximately the same amount of effort.

Thoughts @scotthue

Once implemented on the Results page adding this to other places where we display date/time would not be much effort.

**Comment by scotthue** [comment]
Browser might not always be in the right time zone because often the
directors are coming from somewhere else.

**Comment by rdunlop** [comment]
Note: PDF printing stlil doesn't work....see https://wkhtmltopdf.org/usage/wkhtmltopdf.txt for documentation about the `[date]` and `[time]` templates
